### ISSUE TITLE
Compatible with 5.2.1? (5.x series?)

### ISSUE THREAD

**Issue by kngs** [JMAConsulting/biz.jmaconsulting.bugp#59]
Hi,

Is this version compatible with the 5.x series (in particular 5.2.1)?

I'm at 4.7.27 and running 1.3.1 of this extension (about to upgrade to 5.2.1).
Prior to upgrade it says there is an update available to 1.3.3 but when I try and upgrade it returns me to the extensions screen and indicates an upgrade is still available. That new version says it is compatible with 4.7.28 (which I'm not at yet so I assume that's why it didn't upgrade).
I don't want to go to 5.2.1 unless this extension is compatible.

Thanks for letting me know!

P.S. Also curious if the Grants Application and Prints Grants as PDF extensions are also 5.x compatible, as this client uses them all :)

**Comment by kngs** [comment]
I guess there is a version ONLY compatible with 4.7.28 (nothing older or more recent).  I've upgraded Civi to 5.3.1 and it still won't upgrade.

**Comment by Edzelopez** [comment]
Sorry for the delay on replying to this @kngs 
The extension should ideally work with 5.x, but we haven't tested it yet. I will look into the upgrade issue in sometime, and will release a version compatible for 5.x if necessary.

**Comment by Edzelopez** [comment]
We are working on a 5.x release for the Grant application extension, and will also work on a release for Print Grants as PDF after that :)

**Comment by mikantchap** [comment]
This doesn't work with CiviCRM 5.8.2. If you try to edit a profile you get the following errors at the point you try to save the profile:


Notice: Undefined offset: 2 in CRM_UF_Form_Field->postProcess() (line 554 of /home/salfordcvsco/public_html/sites/all/modules/civicrm/CRM/UF/Form/Field.php).
--

ArgumentCountError: Too few arguments to function CRM_Core_BAO_UFField::duplicateField(), 1 passed in /home/salfordcvsco/public_html/sites/all/modules/civicrm/CRM/UF/Form/Field.php on line 562 and exactly 2 expected in CRM_Core_BAO_UFField::duplicateField() (line 128 of /home/salfordcvsco/public_html/sites/salfordcvs.co.uk/civicrm_extensions/biz.jmaconsulting.bugp-1.3.2/CRM/Core/BAO/UFField.php).

We will have to disable this extension for now I guess? We have to use 5.x CiviCRM because we have to use PHP 7.1 due to security.

**Comment by JoeMurray** [comment]
@Edzelopez Could you work on removing the override file as https://github.com/JMAConsulting/biz.jmaconsulting.bugp/blob/master/CRM/Core/BAO/UFField.php#L128 has become out of date with https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/BAO/UFField.php#L204 long ago. Then tag a new release.
